### ISSUE TITLE
error  "failed to fetch file at path \"main\""

### ISSUE THREAD

**Issue by DogeWatch** [cs01/gdbgui#52] opened 2017-03-20 14:43 UTC
And there is another error:  1490015500998	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."

**Comment by cs01** [comment] 2017-03-20 17:07
> error "failed to fetch file at path \"main\""

This means gdb was not able to determine which file was associated with the function `main`, so it told gdbgui the path was `main`. gdbgui then complains that it can't find it (because there isn't a file named "main", which is true).

Are you debugging with rust or go? You might want to disable the "auto add breakpoint to main" since gdb doesn't do a good job determining files from function names with those languages.

>1490015500998	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."

I have not encountered this error. Where are you seeing it? Which process is raising it? What are you doing when it occurs?

**Comment by cs01** [comment] 2017-03-30 00:25
Anything else I can help with here? Have the issues been resolved?

**Comment by sharazam** [comment] 2017-04-18 09:46
How do you disable "auto add breakpoint to main" ? Getting the same error on a Rust executable.

How do I need to set up the source files / source directory for gdbgui to work? I have the target executable in `/target/debug/myexecutable`. And the source in `/src/main.rs`. GDB can find the file, it I type `break main:9`, it sets a breakpoint in main.rs at line 9. However gdbgui just gives an error ` failed to fetch file at path "undefined" `. Not sure how to fix this.

**Comment by sharazam** [comment] 2017-04-18 10:03
It seems like you have to load the file seperately in the *second* dropdown. 

Inspecting a local variable still does not work it results in `Error occured on server when running gdb command: [Errno 32] Broken pipe`. 

Restarted gdbgui. Now it's stuck on `fetching source files for inferior program. For very large executables, this may cause gdbgui to freeze.`. My program is 30 lines and it's been stuck like this for minutes. 

Restarted again. Apparently, if you initialize gdbgui with a console command like `gdbgui ./myexecutable`, it can load the files, otherwise it gets stuck. Set breakpoint, hit reload button. `No symbol 'fflush' in current context`. Tried to inspect local variable - `error Error occured on server when running gdb command: [Errno 32] Broken pipe`.

So far I've not been able to inspect a single variable using gdbgui.

**Comment by cs01** [comment] 2017-04-18 16:49
@sharazam sorry gdbgui has given you such a hard time. The goal of gdbgui is to make developing _more_ pleasant and efficient, so hopefully I can help with the issues you've been seeing.

> How do you disable "auto add breakpoint to main" ?
In the top right corner there is a gear icon, click it, then check/uncheck `Auto add breakpoint to main`

> How do I need to set up the source files / source directory for gdbgui to work? 

It shouldn't matter where the source files are located, so long as when you compile, you do so with the `-g` flag. Read more [here](http://www.delorie.com/gnu/docs/gdb/gdb_17.html).

> it I type break main:9, it sets a breakpoint in main.rs at line 9. However gdbgui just gives an error failed to fetch file at path "undefined". Not sure how to fix this.

I commented on this [above](https://github.com/cs01/gdbgui/issues/52#issuecomment-287828246), but basically gdb cannot currently determine file names from function names when using rust or go. I expect the gdb core team will fix this as support for rust and go matures. 

The way to fix this is:

1. Uncheck `Auto add breakpoint to main` in gdbgui's settings
1. Compile your rust executable with the `-g` flag (see [gdbgui/examples](https://github.com/cs01/gdbgui/blob/master/examples/makefile))
1. Load the executable in gdbgui either by clicking `Load This Binary and Args` button, or by passing it in via a commandline argument (as you did)
1. Click the file dropdown, then load the file in which you want to set a breakpoint
1. Click in the gutter to set a breakpoint
1. Run the program by clicking the circular arrow icon in the top right

>  Now it's stuck on fetching source files for inferior program. For very large executables, this may cause gdbgui to freeze.. My program is 30 lines and it's been stuck like this for minutes.

There have been reports of it freezing for 100,000+ LOC (https://github.com/cs01/gdbgui/issues/29), but there is no way this should take more than a few (milli) seconds in general. I am guessing there was some sort of error -- maybe the `Broken pipe` error --on the server, and it was not actually doing anything while you were waiting.

>  Set breakpoint, hit reload button. No symbol 'fflush' in current context. 

`fflush` is automatically called by gdbgui to flush stdout and stderr so output of the inferior program can be presented immediately to the user. In off-nominal cases you might get errors regarding `fflush`, but it works well in normal circumstances. If you keep getting this error let me know.

I just followed the steps listed, and took a screenshot of `gdbgui/examples/hello.rs` (you can also see that variable inspection works):

![image](https://cloud.githubusercontent.com/assets/5715368/25142357/706f5eee-241b-11e7-8efb-6621b4ed7ac1.png)

Again, sorry for the frustration. I appreciate you giving it a shot. Let me know if any of this helps. If so, I'll try to code around your difficulties so it doesn't bite more people in the future.

If this does not help, I would ask which versions of 

* gdb
* operating system/kernel version
* python 

you are using. Thanks!

**Comment by cs01** [comment] 2017-04-23 15:15
@sharazam checking in to see if this helped at all, please let me know

**Comment by sharazam** [comment] 2017-04-23 15:25
Sorry, did not respond. It did not help on my laptop, errors are reproducible - gdbgui hangs when started without the executable name. Still the same issues I described. I mainly used gdbgui because there was an issue getting the TUI mode in GDB to work. I got the TUI to work now and used that instead to debug my stuff.

I'll try again on my desktop, but I personally don't need gdbgui anymore, I'm fine with the TUI mode of GDB.

**Comment by cs01** [comment] 2017-04-23 18:45
Made some improvements that should help. If you get around to trying it, let me know. If not, no problem.

**Comment by cs01** [comment] 2017-04-24 16:27
@DogeWatch If you are still watching this issue let me know if this fixed it. If not, let me know and I'll close it out.

**Closed** 2017-05-22 19:27 UTC

**Comment by zoechi** [comment] 2017-12-31 16:57
I disabled auto add breakpoint but I still get

> No source file named /Users/zoechi/dart/rust/playground/hello_world_1/src/main.rs.

**Comment by cs01** [comment] 2017-12-31 23:46
@zoechi thanks for reporting this. Can you open a new issue and provide additional details? Answers to the following that will help me figure out how to fix this: 

* Do any source files successfully load?
* Does this only occur on startup?
* What is your environment (gdb version, gdbgui version, pip freeze output, etc)
* Steps to replicate
