### ISSUE TITLE
Crashes on 600+ source files

### ISSUE THREAD

**Issue by iAbadia** [cs01/gdbgui#232] opened 2018-09-24 14:49 UTC
**Description**
When I load a binary produced from A LOT of source files and try to fetch them to set a breakpoint in a file different from the main, I get the error that gdb is not responding. Also, I get the following message in the filesystem window after clicking the Fetch Files button:

Maximum entries in tree below is 300 (hiding 326). All files can still be searched for in the input above.

**To Reproduce**
Load Binary
Click show filesystem
Click Fetch Source Files
Wait 10 seconds until message shows

**Expected behavior**
I would expect a list of files to show so i can pick the one I want

**Please complete the following information:**
* OS: Running on RHEL VM, connecting from Windows machine
* gdbgui version (`gdbgui -v`): 0.13.0.0
* gdb version (`gdb -v`): GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
* browser [e.g. chrome, safari]: Chrome and Firefox
* python packages (`pip freeze`):
appdirs==1.4.3
asn1crypto==0.24.0
certifi==2018.8.24
cffi==1.11.5
click==6.7
colorama==0.3.9
cryptography==2.3.1
Flask==0.12.4
Flask-Compress==1.4.0
Flask-SocketIO==2.9.6
future==0.16.0
gdbgui==0.13.0.0
gevent==1.3.6
greenlet==0.4.15
idna==2.7
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
pycparser==2.18
pygdbmi==0.8.3.0
Pygments==2.2.0
python-engineio==2.2.0
python-socketio==2.0.0
python-telegram-bot==11.1.0
six==1.11.0
telegram-send==0.20
Werkzeug==0.14.1

**Comment by cs01** [comment] 2018-09-24 16:27
The message you mentioned is a warning that should say it can be ignored if an operation is taking a long time (and in this case it is). 

The 300 cap on the file tree is by design too so that it doesn’t slow down the UI performance.  You can still search through all the source files above the file tree in the input.

Overall it sounds like everything is working by design.

**Comment by iAbadia** [comment] 2018-09-24 22:17
I might have forgotten to mention that gdb was no longer working properly after that. Switched to gdb 8.0.1 and it's all working fine. There's definitely something wrong with gdb 7.2 but since it's kinda old it might not be worth looking into it.

**Comment by cs01** [comment] 2018-09-25 04:27
Ah I see. Yeah I have not tested with that version of gdb.  Thanks for the feedback though, glad you got it working.  I’m going to close the issue.  Let me know if anything else comes up.

**Closed by cs01** 2018-09-25 04:27 UTC
