### ISSUE TITLE
Problems using ARM cross GDB toolchain

### ISSUE THREAD

**Issue by mbolivar** [cs01/gdbgui#154] opened 2018-01-10 04:50 UTC
##### Describe the issue

I'm trying to use gdbgui to debug ELF binaries generated using a cross GCC toolchain for the Zephyr RTOS (https://www.zephyrproject.org/).

My strategy is to use a gdbserver instance running on my localhost which is connected to my embedded target (an ARM Cortex M-4). The gdbserver instance exposes a local port. This is working fine using the command line tools.

I had this kind-of-but-not-really working in earlier versions of gdbgui (not sure which, unfortunately), but there seems to have been a regression in 0.10.0, and I can't even attach to the gdbserver anymore.

##### Steps to replicate

First, I try loading the binary manually:

```
$ /usr/bin/arm-none-eabi-gdb /home/mbolivar/src/zephyr/build/zephyr/zephyr.elf
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/mbolivar/src/zephyr/build/zephyr/zephyr.elf...done.
(gdb) 
```

No problems there. I can then attach to the gdbserver which I've started already, and thus the inferior target:

```
(gdb) tar rem :3333
Remote debugging using :3333
k_cpu_idle () at /home/mbolivar/src/zephyr/arch/arm/core/cpu_idle.S:135
135		bx lr
```

I then start gdbgui 0.10.0 with the same gdb, like so:

```
gdbgui -g /usr/bin/arm-none-eabi-gdb
```

Then I enter the same absolute path (/home/mbolivar/src/zephyr/build/zephyr/zephyr.elf) in the gdbgui "Load Binary" text box, and click that button. I get:

```
gdbgui spawned subprocess with pid 13454 from executable /usr/bin/arm-none-eabi-gdb.

gdb process 13454 is running for this tab

GNU gdb (GDB) 8.0.1

Copyright (C) 2017 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.

This GDB was configured as "--host=x86_64-pc-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.


For bug reporting instructions, please see:

<http://www.gnu.org/software/gdb/bugs/>.

Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".

Type "apropos word" to search for commands related to "word".

File not found: main
```

##### Describe your environment

* Operating system and version:

I am running the latest arm-none-eabi-gdb available on Arch Linux x86_64, which is currently based on GDB 8.0.1 as shown above.

* gdbgui version (`gdbgui -v`):

```
$ gdbgui -v
0.10.0.2
```

* gdb version (`gdb -v`):

```
$ /usr/bin/arm-none-eabi-gdb -v
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
```

* browser: Chrome Version 63.0.3239.108 (Official Build) (64-bit)
* python packages (`pip freeze`): https://gist.github.com/mbolivar/1646329580ab189c23a48bb1b29c1bdc

**Comment by mbolivar** [comment] 2018-01-10 04:54
By the way, I think gdbgui has the potential to be a really killer app in the open source embedded world. We're mostly stuck between massive (usually Eclipse-based) IDEs provided by SOC vendors, proprietary IDEs provided by ARM et al, and the command line GDB tools here.

It'd be really awesome to see gdbgui succeed in this area. Please let me know if there's more info I can provide which might make this easier to debug, and I'd be happy to.

**Comment by cs01** [comment] 2018-01-10 06:24
Thanks for the detailed report.

What is the actual error? I see you get the error "File not found: main". This is because gdbgui automatically runs the command "break main" after loading a binary, but it isn't any type of show-stopping error. 

I'm not sure I understand your setup, but could you explain why using the "connect to gdbserver" button doesn't work, why gdbserver isn't running on your RTOS, and how gdbserver is connected to the RTOS? TBH I have not used gdbgui in the embedded world, so I may learn something from you :)
![image](https://user-images.githubusercontent.com/5715368/34757528-b3045114-f586-11e7-80fd-0e5de22c56e7.png)

Also, I would recommend going to Settings in gdbgui and turning on the option `Print all sent commands in console, including those sent automatically by gdbgui`. This way, you can see exactly what is being sent by gdbgui. You can also run the same commands you had working in command line gdb, but manually in gdbgui and see if it works that way. 

In regard to your second comment, I am glad to hear it. I agree that existing solutions feel a little clunky, which is why I started the project in the first place, so I'm very pleased that it's working (at least somewhat) for you. And please keep filing issues! The best way to make gdbgui better is to let me know your use case and pain points so I can address them. It's impossible for me know to know all the various ways gdb is used.

**Comment by mbolivar** [comment] 2018-01-10 07:20
> What is the actual error? I see you get the error "File not found: main". This is because gdbgui automatically runs the command "break main" after loading a binary, but it isn't any type of show-stopping error.

Sorry for the bad report. The behavior already indicates errors which don't occur in command line tool sessions those commands, FWIW.

```
$ /usr/bin/arm-none-eabi-gdb -q /home/mbolivar/src/zephyr/build/zephyr/zephyr.elf
Reading symbols from /home/mbolivar/src/zephyr/build/zephyr/zephyr.elf...done.
(gdb) tar rem :3333
Remote debugging using :3333
k_cpu_idle () at /home/mbolivar/src/zephyr/arch/arm/core/cpu_idle.S:135
135		bx lr
(gdb) break main
Breakpoint 1 at 0x3c (2 locations)
(gdb) info break
Num     Type           Disp Enb Address    What
1       breakpoint     keep y   <MULTIPLE> 
1.1                         y     0x0000003c <_vector_table+60>
1.2                         y     0x00000644 in main 
                                           at /home/mbolivar/src/zephyr/samples/hello_world/src/main.c:12
(gdb) 
```

> I'm not sure I understand your setup, but could you explain why using the "connect to gdbserver" button doesn't work, why gdbserver isn't running on your RTOS, and how gdbserver is connected to the RTOS? TBH I have not used gdbgui in the embedded world, so I may learn something from you :)

These targets are the sort of deeply embedded microcontroller CPU that's too small to run gdbserver on the same chip which is running the program you're interested in debugging. Instead, you connect to that microcontroller over a chip-to-chip debug protocol (usually SWD) through some secondary chip, the debug IC, which usually interacts with a gdbserver process on the host machine via USB.

Looks like this:

```
workstation / debug host running gdbserver <--- USB ---> debug secondary IC <----  chip to chip debug protocol (on ARM, usually SWD) ---> chip with program being debugged
```

The "chip to chip debug protocol" is a real chip-to-chip protocol, i.e. the debug IC directly controls the chip being debugged using a direct hardware link. Think of a headcrab from the Aliens movies: the debug IC, through direct hardware signalling, tells the chip being debugged when to step a single instruction via the SWD protocol, and can read out memory and other state using the same protocol.

All of these details are hidden behind the common gdbserver protocol which is run on the host PC. The gdbserver instance knows how to translate the common network protocol expected by GDB and the USB/etc commands expected by the embedded development environment.

The workstation / debug host is the computer which runs gdbserver. This is the "normal computer" which runs Linux, macOS, Windows, etc.

In this case, I'm using the gdbserver provided by pyOCD (https://github.com/mbedmicro/pyOCD), but there are numerous examples of gdbservers in this area. One important example is https://www.segger.com/products/debug-probes/j-link/tools/j-link-gdb-server/about-j-link-gdb-server/.

There are numerous other gdbserver implementations in this area, though. Beyond J-Link, the Black Magic Debug Probe has one, and there are other examples.

> Also, I would recommend going to Settings in gdbgui and turning on the option Print all sent commands in console, including those sent automatically by gdbgui. This way, you can see exactly what is being sent by gdbgui. You can also run the same commands you had working in command line gdb, but manually in gdbgui and see if it works that way.

Awesome, thanks for the pointer. Here's what I get:

```

gdbgui spawned subprocess with pid 24248 from executable /usr/bin/arm-none-eabi-gdb.

gdb process 24248 is running for this tab

GNU gdb (GDB) 8.0.1

Copyright (C) 2017 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.

This GDB was configured as "--host=x86_64-pc-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.


For bug reporting instructions, please see:

<http://www.gnu.org/software/gdb/bugs/>.

Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".

Type "apropos word" to search for commands related to "word".

-exec-arguments 

-file-exec-and-symbols /home/mbolivar/src/zephyr/build/zephyr/zephyr.elf

-break-insert main

-break-list

-break-list

File not found: main
```

Here's some results:

```
$ /usr/bin/arm-none-eabi-gdb -q -exec-arguments
/usr/bin/arm-none-eabi-gdb: unrecognized option '-exec-arguments'
Use `/usr/bin/arm-none-eabi-gdb --help' for a complete list of options.

$ /usr/bin/arm-none-eabi-gdb -q --exec-arguments
/usr/bin/arm-none-eabi-gdb: unrecognized option '--exec-arguments'
Use `/usr/bin/arm-none-eabi-gdb --help' for a complete list of options.
```

Sorry if it's a rookie follow-up, but what am I missing?

**Comment by mbolivar** [comment] 2018-01-10 07:26
> In regard to your second comment, I am glad to hear it. I agree that existing solutions feel a little clunky, which is why I started the project in the first place, so I'm very pleased that it's working (at least somewhat) for you. And please keep filing issues! The best way to make gdbgui better is to let me know your use case and pain points so I can address them. It's impossible for me know to know all the various ways gdb is used.

Keeping this a separate response since it's not directly about the issue, but let me encourage you to keep at it!

This is the sort of thing people in my area have been hoping to see for some time. I shared some gdbgui screenshots when I had the previous version successfully attached to my target with colleagues, and they were really interested. I had trouble with continuing to breakpoints on that past version which prevented me from chasing it down more carefully, but I really believe the concept is way overdue and you've got all the UI you need to be very relevant here.

I understand, though, that this may be a very fragmented niche you're not able to pursue at first. If so, I wish you the best and hope you have time to look at embedded in later days.

**Comment by mbolivar** [comment] 2018-01-10 07:39
> The behavior already indicates errors which don't occur in command line tool sessions for those commands, FWIW.

IMO this is the first anomaly to investigate. Why does running the cross GDB directly produce a different result than running it under gdbgui?

I don't know of a good way to post binaries, but here's a ZIP file containing the ELF I compiled which resulted in an error under gdbgui.

[zephyr.zip](https://github.com/cs01/gdbgui/files/1617866/zephyr.zip)

Just in case you're in the majority of the world not running Arch Linux, the ARM tools (including arm-none-eabi-gdb) also have binaries available for multiple platforms here: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm

**Comment by cs01** [comment] 2018-01-10 17:45
Can you post a transcript of the command line session that works, as well as a transcript of the gdbgui session and what the error is? If the only error is the message `File not found: main`, that's something I can fix in gdbgui. You can also turn this off by unchecking Settings > Add breakpoint to main after loading executable.

> IMO this is the first anomaly to investigate. Why does running the cross GDB directly produce a different result than running it under gdbgui?

In gdbgui are you connecting to the remote target or just loading the elf binary? It looks like in the commandline session you're running gdb, loading .elf symbols, then connecting to the remote target. But in gdbgui it looks like you are running gdbgui, loading .elf symbols, and then attempting to break at main. Is this correct?

The reason you're getting `/usr/bin/arm-none-eabi-gdb: unrecognized option '-exec-arguments'` is because gdb needs to be launched with the `--interpreter=mi2` flag to understand [machine interface](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html) commands, such as the ones gdbgui sends like `-exec-arguments`.

**Comment by mbolivar** [comment] 2018-01-16 04:56
Hi again, thanks for the response!

I'm retesting this on a work machine running Ubuntu 17.10.

> Can you post a transcript of the command line session that works, as well as a transcript of the gdbgui session and what the error is? If the only error is the message File not found: main, that's something I can fix in gdbgui. You can also turn this off by unchecking Settings > Add breakpoint to main after loading executable.

Here is a working transcript when run manually:

https://gist.github.com/mbolivar/ee57e860e1543cc55c5e87e079acbe53#file-working

I then try the following.

1. `gdbgui -g /usr/bin/arm-none-eabi-gdb`
2. Type `/home/mbolivar/src/zephyr/build/zephyr/zephyr.elf` and press the "Load Binary" button

Then it does look like the error message is spurious, as I can get a similar session running commands manually in the text box prompting "enter gdb command", despite the "File not found: main" error:

https://gist.github.com/mbolivar/ee57e860e1543cc55c5e87e079acbe53#file-with-error

If I don't use the "Load binary" button, but use "file" manually in the text prompt:

https://gist.github.com/mbolivar/ee57e860e1543cc55c5e87e079acbe53#file-without-error 

This doesn't contain the unexpected "File not found: main" error.

> In gdbgui are you connecting to the remote target or just loading the elf binary? It looks like in the commandline session you're running gdb, loading .elf symbols, then connecting to the remote target. But in gdbgui it looks like you are running gdbgui, loading .elf symbols, and then attempting to break at main. Is this correct?

I hope the above clears up what the behavior is in the various cases. It does seem like the problem is the "Load Binary" button.

> 
> The reason you're getting /usr/bin/arm-none-eabi-gdb: unrecognized option '-exec-arguments' is because gdb needs to be launched with the --interpreter=mi2 flag to understand machine interface commands, such as the ones gdbgui sends like -exec-arguments.

Sorry, I don't understand:

```
$ gdbgui -g /usr/bin/arm-none-eabi-gdb --interpreter=mi2
usage: gdbgui [-h] [-p PORT] [--host HOST] [-r] [-g GDB] [--rr] [--lldb] [-v]
              [--hide_gdbgui_upgrades] [--debug] [-n] [-x GDB_CMD_FILE]
              [--args ARGS [ARGS ...]] [--auth] [--auth-file AUTH_FILE]
              [--license LICENSE] [--key KEY] [--cert CERT]
              [cmd [cmd ...]]
gdbgui: error: unrecognized arguments: --interpreter=mi2
```

```
$ gdbgui -g '/usr/bin/arm-none-eabi-gdb --interpreter=mi2'
 gdb executable "/usr/bin/arm-none-eabi-gdb --interpreter=mi2" was not found. Verify the executable exists, or that it is a directory on your $PATH environment variable.
try "sudo apt-get install gdb" for Linux or "brew install gdb"
```

**Comment by mbolivar** [comment] 2018-01-16 04:56
I should clarify that I restart the GDB server in another terminal each time I connect to the remote.

**Comment by cs01** [comment] 2018-01-16 05:13
Is the error simply that you are getting a message that says `File not found: main`?

**Comment by cs01** [comment] 2018-01-16 05:20
Regarding the `--interpreter=mi2`, I was saying when running the command `-exec-arguments` in gdb, gdb needs to be launched like so: `gdb --interpreter=mi2`. 

This is only useful for when you were trying to run gdbgui commands in the plain terminal gdb process (in other words, do not launch gdbgui with that argument. Launch gdb itself w/ that argument to run machine interface commands.)

**Comment by cs01** [comment] 2018-01-27 20:53
It looks like the only error you're getting is `File not found: main`. That's because gdbgui tries to add a breakpoint to main when it loads a binary or connects to a gdbserver. This can be turned off in settings if desired. Sometimes gdb tries to set the breakpoint and for some reason (usually it does not know the address of the main function) it can't, and that's the message you're seeing. I am going to close this ticket, as this is expected behavior.

**Closed by cs01** 2018-01-27 20:53 UTC
