### ISSUE TITLE
Python NameError in console during gdb step

### ISSUE THREAD

**Issue by cjdrake** [cs01/gdbgui#228] opened 2018-08-22 19:59 UTC
**Describe the bug**
I am debugging a C++ binary, and this string is continuously being printed to the console:

Python Exception <class 'NameError'> name 'long' is not defined:

Other than that, things seem to be working fine. The error seems to be trapped, and life goes on.

This is in release 13.0.0.0, using Python 3.5.3. The browser is Chrome.

**To Reproduce**

**Expected behavior**

**Screenshots**
![screenshot from 2018-08-22 12-50-14](https://user-images.githubusercontent.com/1093960/44487296-cd5b5a00-a60a-11e8-9eac-e7ac034a3929.png)

**Please complete the following information:**
* OS: Linux Debian variant
* gdbgui version (`gdbgui -v`): 0.13.0.0
* gdb version (`gdb -v`): 7.12.0.20161007-git
* browser [e.g. chrome, safari]: chrome
* python packages (`pip freeze`):
click==6.7
Flask==0.12.4
Flask-Compress==1.4.0
Flask-SocketIO==2.9.6
gdbgui==0.13.0.0
gevent==1.3.6
greenlet==0.4.14
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
pkg-resources==0.0.0
pygdbmi==0.8.3.0
Pygments==2.2.0
python-engineio==2.2.0
python-socketio==2.0.0
six==1.11.0
Werkzeug==0.14.1

**Additional context**
Wish I could be more specific about usage details.

**Comment by cs01** [comment] 2018-09-30 04:03
Thanks for reporting this. It looks similar to https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-02/msg00849.html.

> probably gdb is executing scripts using python3 and some script doesn't account for the fact
that only "long" and "int" types got merged  in Python3 world and "long" no longer exists.

These scripts are unrelated to gdbgui's python files. Looks like perhaps a newer version of gdb will fix the issue.

I'm going to close, but please update if you find the root cause of the problem, or if you think this shouldn't be closed.

**Closed by cs01** 2018-09-30 04:03 UTC
