### ISSUE TITLE
Failed with TypeError

### ISSUE THREAD

**Issue by caedmon-kitty** [cs01/gdbgui#382] opened 2021-03-09 23:56 UTC
**Describe the bug**
% gdbgui
Opening gdbgui with default browser at http://127.0.0.1:5000
View gdbgui dashboard at http://127.0.0.1:5000/dashboard
exit gdbgui by pressing CTRL+C
Opening in existing browser session.
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.9/site-packages/gevent/baseserver.py", line 246, in _do_read
    self.do_handle(*args)
  File "/home/me/.local/lib/python3.9/site-packages/gevent/baseserver.py", line 208, in do_handle
    spawn(_handle_and_close_when_done, handle, close, args)
  File "src/gevent/greenlet.py", line 662, in gevent._greenlet.Greenlet.spawn
TypeError: type() takes 1 or 3 arguments
2021-03-09T23:41:36Z ((('127.0.0.1', 59874),), <WSGIServer at 0x7f3d22eb5df0 fileno=5 address=127.0.0.1:5000>) failed with TypeError

**To Reproduce**
1.  Install gdbgui using pip per installation guide.
2.  cd to directory with application to be debugged
3.  type "gdbgui"

**Expected behavior**
gdbgui runs

**Screenshots**
N/A.  Does not get to opening a window in the browser.

**Please complete the following information:**
* OS: Fedora 33
* gdbgui version (`gdbgui -v`): 0.14.0.2
* gdb version (`gdb -v`):
* browser [e.g. chrome, safari]: chrome
* python packages (`pip freeze`):

**Additional context**
Python 3.9.2

**Comment by rishubn** [comment] 2021-03-12 19:58
I am experiencing the same issue with Fedora and python 3.9

**Comment by zskelton** [comment] 2021-03-16 14:39
Same issue here on Kali under WSL and Python 3.9.2.

**Comment by JorisHartog** [comment] 2021-03-23 17:32
Same on MacOS Big Sur with Python 3.9.2

**Comment by jasa** [comment] 2021-04-05 15:30
Use `--debug` or `export PURE_PYTHON=1` as workaround.

**Comment by lukehutch** [comment] 2021-05-18 02:40
I needed to add `--debug` to fix this issue when using `pip install gdbgui` on Fedora 33. However, this option seems to be no longer needed with the prebuilt binary available on the latest release page. Please test if you have experienced this problem before (maybe this bug can be closed now).

**Comment by CommonLoon102** [comment] 2021-05-23 17:31
This is a duplicate of https://github.com/cs01/gdbgui/issues/359
You can also find there a workaround for the problem.

**Comment by rileyrg** [comment] 2021-06-21 05:43
while it's open just to add debian 11 same.

 

> ~ gdbgui
> Opening gdbgui with default browser at http://127.0.0.1:5000
> View gdbgui dashboard at http://127.0.0.1:5000/dashboard
> exit gdbgui by pressing CTRL+C
> Traceback (most recent call last):
>   File "/home/rgr/.local/pipx/venvs/gdbgui/lib/python3.9/site-packages/gevent/baseserver.py", line 246, in _do_read
>     self.do_handle(*args)
>   File "/home/rgr/.local/pipx/venvs/gdbgui/lib/python3.9/site-packages/gevent/baseserver.py", line 208, in do_handle
>     spawn(_handle_and_close_when_done, handle, close, args)
>   File "src/gevent/greenlet.py", line 662, in gevent._greenlet.Greenlet.spawn
> TypeError: type() takes 1 or 3 arguments
> 2021-06-21T05:41:30Z ((('127.0.0.1', 53032),), <WSGIServer at 0x7f4aa8320850 fileno=5 address=127.0.0.1:5000>) failed with TypeError

**Comment by cs01** [comment] 2021-08-30 04:50
eventlet and gevent have been removed as dependencies. This should work fine now in v0.15. Thanks everyone for reporting.

**Closed by cs01** 2021-08-30 04:50 UTC
